Repository BUCTSNC/LaptopLecture, pull requests merged in 2024-10, with the labels that each got.

#8 更新ppt内容至10月份版本
  华硕无畏 15 Pro.png
  暗影精灵 乐享版.png
  机械革命 无界14X.png
  机械革命—无界14X.png
Labels: size/XS

#10 Add tablet and router and update some goods
  images/recommendation/laptop/gaming/宏碁-暗影骑士·龙 16 2024.png
  images/recommendation/laptop/gaming/暗影精灵 乐享版.png
  images/recommendation/laptop/igpu/华硕无畏 15 Pro.png
  images/recommendation/laptop/igpu/机械革命-无界 15X 锐龙版.png
  images/recommendation/laptop/igpu/机械革命—无界14X.png
  images/recommendation/laptop/igpu/火影-众颜 U4B 锐龙版.png
  images/recommendation/laptop/igpu/火影-众颜 U6 锐龙版.png
  pages/hardware/recommendation/laptop/gaming.json
  pages/hardware/recommendation/laptop/igpu.json
  pages/hardware/recommendation/router/index.md
  pages/hardware/recommendation/tablet/index.md
  pages/software/index.md
  华硕无畏 15 Pro.png
  暗影精灵 乐享版.png
  机械革命 无界14X.png
  机械革命-无界14 Pro 2024 锐龙版.png
  机械革命—无界14X.png
Labels: size/L

#11 feat: Streamline the software part
  images/360_sample_screenshot.png
  images/ARG.png
  images/SNC_学生实践创新基地.png
  images/SNC_第二课堂人才培养基地.png
  images/WAN.png
  images/campus_net_selfservice_screenshot.jpg
  images/wework_charge_1.png
  images/wework_charge_2.png
  pages/software/index.md
Labels: size/L

#12 fix: 修正图片文件位置及命名
  images/recommendation/laptop/gaming/惠普-暗影精灵 乐享版.png
  images/recommendation/laptop/gaming/暗影精灵 乐享版.png
  images/recommendation/laptop/igpu/华硕-无畏 Pro 15.png
  images/recommendation/laptop/igpu/华硕无畏 15 Pro.png
  images/recommendation/laptop/igpu/机械革命-无界14X.png
  images/recommendation/laptop/igpu/机械革命—无界14X.png
  pages/hardware/recommendation/laptop/gaming.json
  pages/hardware/recommendation/laptop/igpu.json
  华硕无畏 15 Pro.png
  暗影精灵 乐享版.png
  机械革命 无界14X.png
  机械革命-无界14 Pro 2024 锐龙版.png
Labels: size/S

#20 fix(hardware): 删除部分不合适的表述
  pages/hardware/laptop-buying-flow/clearify-requirements.md
  pages/hardware/laptop-buying-flow/faqs/macbook.md
Labels: size/XS

#21 feat: 更新新的签到签退码
  pages/checkin.md
  pages/checkout.md
  pages/signin.md
  public/images/checkin.jpg
  public/images/checkout.jpg
  slides.md
Labels: size/M

#22 fix(software): 对有误事实进行修正，添加沉浸式翻译链接
  pages/software/index.md
Labels: size/S

#23 fix(hardware): 调整部分排版
  pages/hardware/laptop-buying-flow/index.md
  pages/hardware/recommendation/router/index.md
  pages/hardware/recommendation/tablet/index.md
Labels: size/M

#24 feat(theme): 使背景上方的遮罩可选
  theme/layouts/center.vue
  theme/layouts/cols.vue
  theme/layouts/cover.vue
  theme/layouts/default.vue
  theme/layouts/fact.vue
  theme/layouts/full.vue
  theme/layouts/fullpage.vue
  theme/layouts/intro.vue
  theme/layouts/quote.vue
  theme/layouts/section.vue
  theme/layouts/statement.vue
Labels: size/M

#25 feat(hardware/tablet): 移除部分幻灯片上方的背景遮罩
  pages/hardware/recommendation/tablet/index.md
Labels: size/XS
