Repository BUCTSNC/LaptopLecture, pull requests merged in 2024-08, with the labels that each got.

#2 feat(ci): 只为Pull Request运行CI
  .github/workflows/build.yml
Labels: size/XS

#3 feat(ci): 发布 `main` 分支到 GitHub Pages
  .github/workflows/publish.yml
Labels: size/M

#4 fix(ci): publish
  .github/workflows/publish.yml
Labels: size/XS

#5 feat(software): add NFC and X-ware images
  images/NFC1.jpg
  images/NFC2.jpg
  images/NFC3.jpg
  images/NFC4.jpg
  images/X-ware.jpg
  images/rime-ice.webp
  package-lock.json
  pages/software/index.md
Labels: size/L
